# Generated by Django 4.2.7 on 2023-12-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationbar',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
