# Generated by Django 4.2.7 on 2023-12-10 18:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_navigationbar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', ckeditor.fields.RichTextField(blank=True)),
                ('credits_text', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
