# Generated by Django 4.2.7 on 2023-12-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='is_anchor',
        ),
    ]
